---
title: 'DATA 698: Capstone Literature Review'
author: "Derek G Nokes & Paul Britton"
date: "2019-10-08"
output: pdf_document
bibliography: bibliography_lit_review.bib
link-citations: yes
csl: ieee.csl
---


## Literature Review

There is a vast literature on the empirical characteristics of financial markets - including many comprehensive surveys - documenting extensively the basic stylized facts ([-@Bollerslev1992-wg], [-@Brock1996-dp], [-@Shephard1996-gp], [-@Rao1996-ve], [-@Pagan1996-gw], [-@Cont2001-yx], [-@Gourieroux2001-vl], [-@Farmer2009-ye], [-@Marti2017-tp]). Voluminous literature exists detailing different forms of the ‘momentum’ effect ([-@Jegadeesh1993-wd], [-@Moskowitz2012-uy]), the time-varying and serially-dependent nature of return volatility [-@Bollerslev1992-wg], and the hierarchical structure of cross-dependence ([-@Mantegna1999-sn], [-@Tumminello2005-yk], [-@Fenn2011-yl], [-@Caldarelli2016-iy]).

Since the work of Carhart (1997)[-@Carhart1997-gi], the tendency of financial instruments that have performed well (poorly) in the recent past to continue to perform well (poorly) in the near future has been referred to as *momentum*. Financial instruments with the highest returns over the past six to twelve months tend to continue to deliver above-average returns over subsequent months ([-@Jegadeesh1993-wd], [-@Moskowitz2012-uy]). The academic literature distinguishes between two distinct kinds of momentum effects, namely, *time series* (or *absolute*)[-@Moskowitz2012-uy] and *cross-sectional* (or *relative*)[-@Jegadeesh1993-wd]. The former is calculated based on an instrument’s own past return and is considered independently from the returns of other instruments [-@Moskowitz2012-uy], while the latter is a measure of a instrument’s performance, relative to other instruments [-@Jegadeesh1993-wd].

Findings of abnormal returns associated with simple momentum strategies - both relative and absolute - are pervasive [-@Fama2008-ke], spanning essentially all asset classes and geographical regions. Relative momentum effects have been documented in developed ([-@Jegadeesh1993-wd], [-@Asness1994], [-@Rouwenhorst1998-uc], [-@Chan2000-xg], [-@Griffin2005-kf]) and emerging [-@Rouwenhorst1999-pt] market single stocks, industries ([-@Moskowitz1999-cl], [-@Asness2000-kr]), equity indices ([-@Asness1997-fu], [-@Bhojraj2006-ru], [-@Hvidkjaer2006-ey]), commodities ([-@Pirrong2005-cv], [-@Miffre2007-zq]), currencies [-@Menkhoff2012-yy], global government bonds ([-@Asness2013-jb], corporate bonds [-@Jostova2013-as], and residential real estate [-@Beracha2011-pc]. Absolute momentum effects also span multiple asset classes [-@Hurst2017-uy], appearing to be equally robust and universally applicable.

Significant relative momentum effects have been shown out-of-sample going both forward ([-@Grundy2001-ym], [-@Asness2013-jb]) and backward [-@Chabot2008-sn] in time from the original seminal research of Jegadeesh and Titman (1993) [@Jegadeesh1993-wd]. Similarly, meaningful absolute momentum effects are evident for more than a century [-@Hurst2017-uy].

While near ubiquitous, momentum effects are prone to abrupt, albeit temporary, disruptions often referred to as 'momentum crashes' ([-@Barroso2015-fk], [-@Daniel2016-xo]). There is some literature documenting performance improvements resulting from the application of basic controls, but there is not yet much literature about the design of risk controls that exploit return time series characteristics to specifically improve the performance of momentum strategies. Common controls employed by practitioners to improve the risk profile of basic momentum strategies - such as trailing stops and volatility-based position sizing - have received little attention in the academic literature. While there is some theoretical work demonstrating the relative dominance or 'optimality' of volatility-weighting strategies [-@Hallerbach2012-tz], it has only been relatively recently that volatility-based position sizing has been shown in the academic literature to improve the performance of cross-sectional [-@Barroso2015-fk], [-@Daniel2016-xo] and time series [-@Du_Plessis2016-sa] momentum strategies. The use of stop losses for momentum systems has also be justified ([-@Kaminski2014-bc],[-@Lei2009-sc]).

Controls to improve the diversity of the holdings of a momentum trading system, and thereby reduce its portfolio volatility, appear not to have been explored in the academic literature. More specifically, clustering - a form of unsupervised learning used to identify structure in unlabeled data by objectively organizing it into homogeneous groups that minimize within-group-object similarity and maximize between-group-object dissimilarity [-@Warren_Liao2005-rl] - has not yet been used to improve the performance of momentum strategies.

There is an extensive general literature on different clustering methods where the input data objects are time series ([-@Warren_Liao2005-rl], [-@Aghabozorgi2015-zh], and [-@Madiraju2018-ur]). Hierarchical clustering, which groups time series data objects into clusters with a hierarchical or tree-like structure [-@Warren_Liao2005-rl], was applied to historical single stock returns as early as 1966 [-@King1966-zw]. However, it was not popularized in the academic literature pertaining to financial markets until the introduction of the minimal spanning tree (MST) in the seminal work of Mantegna et al ([-@Mantegna1999-sn], [-@Mantegna1999-ul]) decades later.

Over the past two decades, hundreds of articles have been published exploring financial market correlations, hierarchies, networks, and clustering. Researchers have made significant contributions on algorithms ([-@Tumminello2007-te], [-@Aste2005-lv], [-@Tumminello2005-as], [-@Song2011-po], [-@Song2012-xs], [-@Massara2016-dy], [-@Kullmann2000-tw], [-@Giada2001-cv], [-@Giada2002-zw], [-@Plerou2000-gy], [-@MacMahon2015-hh], [-@Kocheturov2014-vj]), distances ([-@Billio_undated-tg], [-@Kenett2010-nw], [-@Fiedor2014-ot], [-@Rocchi2017-eb], [-@Kenett2010-og], [-@Fiedor2014-pf], [-@Rocchi2017-eb], [-@Baitinger_undated-mx], [-@Marti2016-rp], [-@Durante2015-mh], [-@Brechmann_undated-xz], [-@Durante2015-vi], [-@Brida2008-lx], [-@Lee2013-am], [-@Donnat2016-hs]), and other methodological aspects including preprocessing of input time series ([-@Donnat2016-hs], [-@Borghesi2007-js], [@Sensoy2014-cf]) and approaches to assess the reliability and statistical uncertainty of the methods ([-@Marti2015-yx], [-@Tumminello2007-te], [-@Song2011-aj], [-@Tumminello2007-xu], [-@Marti2016-le], [-@Tumminello2007-qo], [-@Papenbrock2015-fh], [-@Panton1976-hf]). The literature pertaining to the dynamics of correlations, hierarchies, networks, and clusters includes the clustering of successive correlation matrices to infer a market state [-@Papenbrock2015-fh], but no applications of such states for portfolio risk control. Topological features [-@Onnela2003-rk] explored to summarize and monitor the time-evolution of a MST include the normalized tree length [-@Onnela2003-hw], the mean occupation layer [-@Onnela2003-hw], the tree half-life [-@Onnela2003-hw], a survival ratio of the edges ([-@Onnela2002-gl], [-@Johnson2005-jf], [-@Sensoy2014-cf]), node degree, strength [-@Sensoy2014-cf], eigenvector, betweenness, closeness centrality [-@Sensoy2014-cf], and the agglomerative coefficient [-@Matesanz2015-sf]. Scaling laws are also explored in several works ([-@Onnela2003-hw], [-@Onnela2002-gl],[-@Vandewalle2001-sa], [-@J_Kim2002-rp], [-@Bonanno2003-vz]). Some applications to portfolio construction ([-@Durante2015-vi], [-@Borghesi2007-js], [-@Onnela2003-hw], [-@Matesanz2015-sf], [-@Onnela2003-hw], [-@Tola2008-ek], [-@Ren2017-ch], [-@Peralta2016-hh], [-@Baitinger2016-by], [-@Leon2017-qr], [-@Prado2016-gp]) and trading strategy development [-@Sandhu2015-ky] also exist, but do not extend to the development of momentum strategies.

Finally, an even broader literature exists on the derivation of financial derivative sensitivities ([-@Merton1973-wi],[-@Black1973-bi]). To price and risk manage products with path-dependent payoffs similar to a momentum strategy, Monte Carlo simulation is often required ([-@Boyle1977-ro], [-@Broadie1996-rm], [-@Longstaff2001-bf]). Despite the link between the analysis of systematic trading strategies and the analysis of replication strategies used to manufacture financial derivative products, little published work exists leveraging the findings in these two areas of research to the analysis of systematic trading strategies([-@Fung2001-uw], [-@Dao2016-od], [-@Jusselin2017], [-@Nokes2019-ea]).

## References


